name: afrisight
description: "Afrisight is a vibrant Flutter app that brings Africa’s rich cultures, countries, and colors to your fingertips with beautiful design and seamless exploration."

publish_to: 'none'  

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  http: ^1.0.0
  get_storage: ^2.1.1
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.3.1
  image_picker: ^1.2.0
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1
  fluttertoast: ^8.2.12
  authentication_buttons: ^0.0.5
  flutter_local_notifications: ^19.4.2
  universal_platform: ^1.1.0
  country_picker: ^2.0.10
  logger: ^2.6.1
  shared_preferences: ^2.5.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/mosaic_logo.png"
  adaptive_icon_background: "#FFFFFF"  
  adaptive_icon_foreground: "assets/images/mosaic_logo.png"
  remove_alpha_ios: true